"""add summary upload relationship

Revision ID: 1fad72440a9d
Revises: 43a1fd48f26b
Create Date: 2026-06-01 13:08:18.259015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fad72440a9d'
down_revision = '43a1fd48f26b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_summary_relationships',
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['summaries.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('upload_id', 'summary_id')
    )
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.alter_column('source_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PDF', 'DOCX', 'TXT', 'CSV', 'XLSX', 'PPTX', 'MARKDOWN', name='filetypes'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.alter_column('source_type',
               existing_type=sa.Enum('PDF', 'DOCX', 'TXT', 'CSV', 'XLSX', 'PPTX', 'MARKDOWN', name='filetypes'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    op.drop_table('upload_summary_relationships')
    # ### end Alembic commands ###
