"""refactor ai content upload tables added new blueprint and attempt table

Revision ID: c6c85a76fbfc
Revises: 3d063b963dcd
Create Date: 2026-07-30 18:31:39.917007

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = "c6c85a76fbfc"
down_revision = "3d063b963dcd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # ------------------------------------------------------------------
    # Create PostgreSQL ENUM types
    # ------------------------------------------------------------------

    ai_content_types = ENUM(
        "SUMMARY",
        "QUIZ",
        "FLASHCARDS",
        "MIND_MAPS",
        "EXAM",
        name="aicontenttypes",
        create_type=False
    )
    ai_content_types.create(op.get_bind(), checkfirst=True)

    processing_status = ENUM(
        "PENDING",
        "PROCESSING",
        "COMPLETED",
        "FAILED",
        name="processingstatus",
        create_type=False
    )
    processing_status.create(op.get_bind(), checkfirst=True)

    evaluation_types = ENUM(
        "QUIZ",
        "EXAM",
        name="evaluationtypes",
        create_type=False
    )
    evaluation_types.create(op.get_bind(), checkfirst=True)

    document_block_type = ENUM(
        "PARAGRAPH",
        "HEADING",
        "TABLE",
        "OCR",
        "CODE",
        "LIST",
        "TRANSCRIPT",
        "DESCRIPTION",
        name="documentblocktype",
        create_type=False
    )
    document_block_type.create(op.get_bind(), checkfirst=True)

    upload_purpose = ENUM(
        "NOTES",
        "REFERENCE",
        name="uploadpurpose",
        create_type=False
    )
    upload_purpose.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "exam_blueprints",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("structure", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table("exam_blueprints", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_exam_blueprints_slug"), ["slug"], unique=True)

    op.create_table(
        "ai_contents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("notebook_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content_type", ai_content_types, nullable=False),
        sa.Column("upload_count", sa.Integer(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["notebook_id"], ["notebooks.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "upload_ai_content_relationships",
        sa.Column("upload_id", sa.String(length=36), nullable=False),
        sa.Column("ai_content_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["ai_content_id"], ["ai_contents.id"]),
        sa.ForeignKeyConstraint(["upload_id"], ["uploads.id"]),
        sa.PrimaryKeyConstraint("upload_id", "ai_content_id"),
    )

    op.create_table(
        "user_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("content_id", sa.String(length=36), nullable=False),
        sa.Column("status", processing_status, nullable=False),
        sa.Column("total_marks", sa.Integer(), nullable=True),
        sa.Column("obtained_marks", sa.Integer(), nullable=True),
        sa.Column("percentage", sa.Double(), nullable=True),
        sa.Column("evaluation_type", evaluation_types, nullable=False),
        sa.Column("evaluation", sa.JSON(), nullable=False),
        sa.Column(
            "evaluated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["content_id"], ["ai_contents.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table("user_attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_attempts_content_id"),
            ["content_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_user_attempts_evaluation_type"),
            ["evaluation_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_user_attempts_status"),
            ["status"],
            unique=False,
        )

    op.drop_table("upload_summary_relationships")
    op.drop_table("summaries")

    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "block_type",
                document_block_type,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "chunk_metadata",
                sa.JSON(),
                nullable=False,
            )
        )

    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "author",
                sa.String(length=255),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "upload_purpose",
                upload_purpose,
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.drop_column("upload_purpose")
        batch_op.drop_column("author")

    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.drop_column("chunk_metadata")
        batch_op.drop_column("block_type")

    op.create_table(
        "summaries",
        sa.Column("id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column(
            "notebook_id",
            sa.VARCHAR(length=36),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "summary_data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "upload_count",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "generated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["notebook_id"],
            ["notebooks.id"],
            name=op.f("summaries_notebook_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("summaries_pkey")),
    )

    op.create_table(
        "upload_summary_relationships",
        sa.Column(
            "upload_id",
            sa.VARCHAR(length=36),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "summary_id",
            sa.VARCHAR(length=36),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["summary_id"],
            ["summaries.id"],
            name=op.f("upload_summary_relationships_summary_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["uploads.id"],
            name=op.f("upload_summary_relationships_upload_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "upload_id",
            "summary_id",
            name=op.f("upload_summary_relationships_pkey"),
        ),
    )

    with op.batch_alter_table("user_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_attempts_status"))
        batch_op.drop_index(batch_op.f("ix_user_attempts_evaluation_type"))
        batch_op.drop_index(batch_op.f("ix_user_attempts_content_id"))

    op.drop_table("user_attempts")
    op.drop_table("upload_ai_content_relationships")
    op.drop_table("ai_contents")

    with op.batch_alter_table("exam_blueprints", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exam_blueprints_slug"))

    op.drop_table("exam_blueprints")

    # Drop enum types
    upload_purpose = ENUM(name="uploadpurpose")
    document_block_type = ENUM(name="documentblocktype")
    evaluation_types = ENUM(name="evaluationtypes")
    processing_status = ENUM(name="processingstatus")
    ai_content_types = ENUM(name="aicontenttypes")

    upload_purpose.drop(op.get_bind(), checkfirst=True)
    document_block_type.drop(op.get_bind(), checkfirst=True)
    evaluation_types.drop(op.get_bind(), checkfirst=True)
    processing_status.drop(op.get_bind(), checkfirst=True)
    ai_content_types.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###